# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Macleay Recipe Manager
# Build locally:
#   python generate_icon.py
#   python create_version_info.py 1.0.0
#   pyinstaller recipe_manager.spec

from PyInstaller.utils.hooks import collect_data_files, collect_submodules
import os

# ── Data files to bundle ──────────────────────────────────────────────────────
datas = [
    ('static', 'static'),
]
datas += collect_data_files('recipe_scrapers')
datas += collect_data_files('extruct', include_py_files=False)

# ── Hidden imports ────────────────────────────────────────────────────────────
hiddenimports = (
    collect_submodules('recipe_scrapers') +
    collect_submodules('flask') +
    collect_submodules('werkzeug') +
    collect_submodules('jinja2') +
    collect_submodules('webview') +
    [
        'pkg_resources.py2_warn',
        'sqlite3',
        'json',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'encodings.utf_8',
        'encodings.ascii',
    ]
)

# ── Icon & version info ───────────────────────────────────────────────────────
# Both files are generated by generate_icon.py / create_version_info.py
# before PyInstaller runs (CI does this automatically).
_icon    = 'icon.ico'              if os.path.exists('icon.ico')              else None
_verfile = 'file_version_info.txt' if os.path.exists('file_version_info.txt') else None

# ── Analysis ──────────────────────────────────────────────────────────────────
a = Analysis(
    ['launcher.py'],
    pathex=[os.path.abspath('.')],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'test', 'unittest'],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='RecipeManager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # No black console window
    icon=_icon,             # Embedded app icon (generated at build time)
    version=_verfile,       # Windows file-properties version info
)
